# Civilization VI Bot - Emoji Configuration
# Users will type these emojis to ban civilizations

CIV_EMOJI_CONFIG = {
    "Abraham Lincoln (Amérique)": "🏭",
    "Alexandre (Macédoine)": "⚔️",
    "Aliénor d'Aquitaine (Angleterre)": "💕",
    "Aliénor d'Aquitaine (France)": "🎶",
    "Amanitoré (Nubie)": "🌞",
    "Ambiorix (Gaule)": "⚜",
    "Bà triêu (Vietnam)": "🐘",
    "Basile II (Byzance)": "✝️",
    "Catherine de Médicis - Reine noire (France)": "🕵️‍♀️",
    "Catherine de Médicis - Spendeur (France)": "🎨",
    "Chaka (Zoulous)": "🦁",
    "Chandragupta (Inde)": "🐅",
    "Christine de Suède (Suède)": "📚",
    "Cléopâtre - Egyptienne (Egypte)": "🐍",
    "Cléopâtre - Ptolémaïque (Egypte)": "💧",
    "Cyrus (Perse)": "🦅",
    "Dame Six Cieux (Maya)": "🌿",
    "Didon (Phénicie)": "⚓",
    "Dyah Gitarja (Indonésie)": "🌊",
    "Elisabeth Ire (Angleterre)": "🏰",
    "Frédéric Barberousse (Allemagne)": "⚒️",
    "Gandhi (Inde)": "☮️",
    "Gengis Khan (Mongolie)": "🐎",
    "Gilgamesh (Sumer)": "👬",
    "Gorgô (Grèce)": "🧿",
    "Hammurabi (Babylone)": "🚬",
    "Harald Hardrade - Konge (Norvège)": "🪓",
    "Harald Hardrade - Varègue (Norvège)": "⛵",
    "Hedwige Ière (Pologne)": "🙏",
    "Hōjō Tokimune (Japon)": "🍣",
    "Jayavarman VII (Peuple Khmer)": "🕉️",
    "Jean III (Portugal)": "🍮",
    "John Curtin (Australie)": "🦘",
    "Jules César (Rome)": "🔪",
    "Kubilai Khan (Chine)": "🐉",
    "Kubilai Khan (Mongolie)": "🏇",
    "Kupe (Maoris)": "🦋",
    "Lautaro (Mapuches)": "🔥",
    "Louis II (Allemagne)": "🎼",
    "Mansa Moussa (Mali)": "💰",
    "Matthias Corvin (Hongrie)": "🦢",
    "Menelik II (Ethiopie)": "⛰️",
    "Ming Yongle (Chine)": "🔨",
    "Moctezuma (Aztèques)": "🌽",
    "Mvemba A Nzinga (Congo)": "⛪",
    "Nader Shah (Perse)": "🗡️",
    "Njinga Mbandi (Congo)": "👸🏿",
    "Pachacutec (Incas)": "🌄",
    "Péricles (Grèce)": "🎭",
    "Philippe II (Espagne)": "🔱",
    "Pierre Ier le Grand (Brésil)": "🚢",
    "Poundmaker (Cris)": "🌾",
    "Qin - Mandat du Ciel (Chine)": "🐲",
    "Qin - unificateur (Chine)": "🏯",
    "Ramsès II - Egypte": "🏺",
    "Robert Bruce (Ecosse)": "🛡️",
    "Saladin - sultan (Arabie)": "☪️",
    "Saladin -vizir (Arabie)": "📜",
    "Sejon (Corée)": "🔠",
    "Seondeok (Corée)": "🌸",
    "Simón Bolívar (Grande Colombie)": "🎖️",
    "Soliman - kanuni (Ottomans)": "⚖️",
    "Soliman - muhtesem (Ottomans)": "👑",
    "Soundiata Keïta (Mali)": "🪘",
    "Tamar (Géorgie)": "🧱",
    "Théodora (Byzance)": "👸",
    "Theodore Roosevelt - Elan (Amérique)": "🐻",
    "Theodore Roosevelt - Rough Rider (Amérique)": "🤠",
    "Tokugawa (Japon)": "💴",
    "Tomyris (Scythie)": "🏹",
    "Trajan (Rome)": "🏛️",
    "Victoria - ère de la vapeur (Angleterre)": "🚂",
    "Victoria - ère impériale (Angleterre)": "🌍",
    "Wilfrid Laurier (Canada)": "🍁",
    "Wilhelmine (Pays-bas)": "🌷",
    "Wu Zetian (Chine)": "🦎"
}

GAME_OPTIONS = {
    "Carte": [
        "Continents",
        "Fractale",
        "Mer Intérieure",
        "Plateaux d'îles",
        "Pangée",
        "Archipel",
        "Sept mers",
        "Petits continents",
        "Lacs",
        "Miroir",
        "Primordial",
        "Terra",
        "Highlands",
        "Marécageux",
        "Rich Highlands (BBM)",
    ],
    "Societées Secretes": [
        "Oui",
        "Non",
    ],
    "Héros et Légendes": [
        "Oui",
        "Non",
    ],
    "Monopoles et Corporations": [
        "Oui",
        "Non",
    ],
    "Ressources (luxes et bonus)": [
        "Eparses",
        "Classiques",
        "Abondantes",
    ],
    "Densité de Merveilles Naturelles": [
        "Eparses",
        "Standard",
        "Abondantes",
    ],
    "Age du Monde (+ d'age = - de montagnes)": [
        "Nouveau",
        "Classique",
        "Vieux",
    ],
    "Climat (Desert vs Toundra/Neige)": [
        "Chaud",
        "Classique",
        "Polaire",
    ],
    "Precipitations (Densitée de bois/Jungle et Marais)": [
        "Aride",
        "Classique",
        "Humide",
    ],
    "Niveau de la Mer (Quantitée d'eau)": [
        "Bas",
        "Classique",
        "Haut",
    ],
    "Camps de Barbares": [
        "Standard (Parametres par defaut sans BBM)",
        "Civilisés (Moins de barbares et pas de barbares montées et navals avant le tour 15)",
        "Equilibrés (Pas de barbares montées avant le tour 15)",
        "Enragés",
        "Pas de barbares",
    ],
}

LEADERS_TO_LINK = {
    "Abraham Lincoln (Amérique)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#America%20Abraham%20Lincoln",
    "Theodore Roosevelt - Elan (Amérique)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#America%20Teddy%20Roosevelt%20%28Bull%20Moose%29",
    "Theodore Roosevelt - Rough Rider (Amérique)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#America%20Teddy%20Roosevelt%20%28Rough%20Rider%29",
    "Saladin -vizir (Arabie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Arabia%20Saladin%20%28Vizier%29",
    "Saladin - sultan (Arabie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Arabia%20Saladin%20%28Sultan%29",
    "John Curtin (Australie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Australia%20John%20Curtin",
    "Moctezuma (Aztèques)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Aztec%20Montezuma",
    "Hammurabi (Babylone)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Babylon%20Hammurabi",
    "Pierre Ier le Grand (Brésil)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Brazil%20Pedro%20II",
    "Basile II (Byzance)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Byzantium%20Basil%20II",
    "Théodora (Byzance)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Byzantium%20Theodora",
    "Wilfrid Laurier (Canada)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Canada%20Wilfrid%20Laurier",
    "Kubilai Khan (Chine)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#China%20Kublai%20Khan%20%28China%29",
    "Qin - Mandat du Ciel (Chine)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#China%20Qin%20%28Mandate%20of%20Heaven%29",
    "Qin - unificateur (Chine)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#China%20Qin%20%28Unifier%29",
    "Wu Zetian (Chine)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#China%20Wu%20Zetian",
    "Ming Yongle (Chine)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#China%20Yongle",
    "Poundmaker (Cris)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Cree%20Poundmaker",
    "Cléopâtre - Egyptienne (Egypte)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Egypt%20Cleopatra%20%28Egyptian%29",
    "Cléopâtre - Ptolémaïque (Egypte)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Egypt%20Cleopatra%20%28Ptolemaic%29",
    "Ramsès II - Egypte": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Egypt%20Ramses%20II",
    "Aliénor d'Aquitaine (Angleterre)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#England%20Eleanor%20of%20Aquitaine%20%28England%29",
    "Elisabeth Ire (Angleterre)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#England%20Elizabeth%20I",
    "Victoria - ère impériale (Angleterre)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#England%20Victoria%20%28Age%20of%20Empire%29",
    "Victoria - ère de la vapeur (Angleterre)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#England%20Victoria%20%28Age%20of%20Steam%29",
    "Menelik II (Ethiopie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Ethiopia%20Menelik%20II",
    "Catherine de Médicis - Reine noire (France)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#France%20Catherine%20de%20Medici%20%28Black%20Queen%29",
    "Catherine de Médicis - Spendeur (France)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#France%20Catherine%20de%20Medici%20%28Magnificence%29",
    "Aliénor d'Aquitaine (France)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#France%20Eleanor%20of%20Aquitaine%20%28France%29",
    "Ambiorix (Gaule)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Gaul%20Ambiorix",
    "Tamar (Géorgie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Georgia%20Tamar",
    "Frédéric Barberousse (Allemagne)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Germany%20Frederick%20Barbarossa",
    "Louis II (Allemagne)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Germany%20Ludwig%20II",
    "Simón Bolívar (Grande Colombie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Gran%20Colombia%20Sim%C3%B3n%20Bol%C3%ADvar",
    "Gorgô (Grèce)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Greece%20Gorgo",
    "Péricles (Grèce)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Greece%20Pericles",
    "Matthias Corvin (Hongrie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Hungary%20Matthias%20Corvinus",
    "Pachacutec (Incas)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Inca%20Pachacuti",
    "Chandragupta (Inde)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#India%20Chandragupta",
    "Gandhi (Inde)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#India%20Gandhi",
    "Dyah Gitarja (Indonésie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Indonesia%20Gitarja",
    "Hōjō Tokimune (Japon)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Japan%20Hojo%20Tokimune",
    "Tokugawa (Japon)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Japan%20Tokugawa",
    "Jayavarman VII (Peuple Khmer)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Khmer%20Jayavarman%20VII",
    "Mvemba A Nzinga (Congo)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Kongo%20Mvemba%20a%20Nzinga",
    "Njinga Mbandi (Congo)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Kongo%20Nzinga%20Mbande",
    "Sejon (Corée)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Korea%20Sejong",
    "Seondeok (Corée)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Korea%20Seondeok",
    "Alexandre (Macédoine)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Macedon%20Alexander",
    "Mansa Moussa (Mali)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Mali%20Mansa%20Musa",
    "Soundiata Keïta (Mali)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Mali%20Sundiata%20Keita",
    "Kupe (Maoris)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#M%C4%81ori%20Kupe",
    "Lautaro (Mapuches)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Mapuche%20Lautaro",
    "Dame Six Cieux (Maya)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Maya%20Lady%20Six%20Sky",
    "Gengis Khan (Mongolie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Mongolia%20Genghis%20Khan",
    "Kubilai Khan (Mongolie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Mongolia%20Kublai%20Khan%20%28Mongolia%29",
    "Wilhelmine (Pays-bas)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Netherlands%20Wilhelmina",
    "Harald Hardrade - Varègue (Norvège)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Norway%20Harald%20Hardrada%20%28Varangian%29",
    "Harald Hardrade - Konge (Norvège)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Norway%20Harald%20Hardrada%20%28Konge%29",
    "Amanitoré (Nubie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Nubia%20Amanitore",
    "Soliman - kanuni (Ottomans)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Ottomans%20Suleiman%20%28Kanuni%29",
    "Soliman - muhtesem (Ottomans)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Ottomans%20Suleiman%20%28Muhtesem%29",
    "Cyrus (Perse)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Persia%20Cyrus",
    "Nader Shah (Perse)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Persia%20Nader%20Shah",
    "Didon (Phénicie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Phoenicia%20Dido",
    "Hedwige Ière (Pologne)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Poland%20Jadwiga",
    "Jean III (Portugal)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Portugal%20Jo%C3%A3o%20III",
    "Jules César (Rome)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Rome%20Julius%20Caesar",
    "Trajan (Rome)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Rome%20Trajan",
    "Robert Bruce (Ecosse)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Scotland%20Robert%20the%20Bruce",
    "Tomyris (Scythie)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Scythia%20Tomyris",
    "Philippe II (Espagne)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Spain%20Philip%20II",
    "Gilgamesh (Sumer)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Sumeria%20Gilgamesh",
    "Christine de Suède (Suède)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Sweden%20Kristina",
    "Bà triêu (Vietnam)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Vietnam%20B%C3%A0%20Tri%E1%BB%87u",
    "Chaka (Zoulous)": "https://civ6bbg.github.io/en_US/leaders_7.2.html#Zulu%20Shaka",
}